language: ruby
rvm:
  - 2.6.3

before_script:
 - chmod +x ./script/cibuild

install: gem install jekyll html-proofer
script: script: jekyll build && htmlproofer ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

cache: bundler

notifications:
  email: false