title: "only One"
description: "only One is a simple Jekyll theme."
permalink: /:title
baseurl: ""
google_analytics: 

exclude: ["vendor", "Rakefile" "README.md", "LICENSE.md", "CHANGELOG.md", "docs"]