title: "only One"
description: "only One is a simple Jekyll theme."
permalink: /:title
baseurl: ""
google_analytics: 

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.md", "CHANGELOG.md", "Rakefile", "docs"]